let productos = [
    {id: 1,
    cantidad: 1,
    nombre:"IPHONE 11",
    img: "images/iphone/iphone_11.jpg",
    precio: 230000,
    categoria:"APPLE"},

    {id: 2,
    cantidad: 1,   
    nombre:"IPHONE 12",
    img: "images/iphone/iphone_12_pro_max.jpg",
    precio: 530000 ,
    categoria:"APPLE"},

    {id: 3,
    cantidad: 1,
    nombre:"IPHONE 13",
    img: "images/iphone/iphone_13.jpg",
    precio: 380000 ,
    categoria:"APPLE"},
    
    {id: 4,
    cantidad: 1,
    nombre:"MOTO G200",
    img: "images/motorola/moto_g200.jpg",
    precio: 110000 ,
    categoria:"MOTOROLA"},
    
    {id: 5,
    cantidad: 1,
    nombre:"MOTO EDGE 20 PRO",
    img: "images/motorola/moto_edge_20_pro.jpg",
    precio: 130000 ,
    categoria:"MOTOROLA"},
    
    {id: 6,
    cantidad: 1,   
    nombre:"MOTO EDGE 30 PRO",
    img: "images/motorola/moto_edge_30_pro.jpg",
    precio: 170000 ,
    categoria:"MOTOROLA"},

    {id: 7,
    cantidad: 1,    
    nombre:"GALAXY S22 ULTRA",
    img: "images/samsung/galaxy_s22_ultra.jpg",
    precio: 268000 ,
    categoria:"SAMSUNG"},
        
    {id: 8,
    cantidad: 1,
    nombre:"GALAXY Z FLIP 3",
    img: "images/samsung/galaxy_z_flip3.jpg",
    precio: 220000 ,
    categoria:"SAMSUNG"},
        
    {id: 9,
    cantidad: 1,   
    nombre:"GALAXY Z FOLD 4",
    img: "images/samsung/galaxy_z_fold_4.jpg",
    precio: 410000 ,
    categoria:"SAMSUNG"},
]